export const Icons = {
  plus: "➕",
  edit: "✏️",
  delete: "🗑️",
  trash: "🗑️",
  check: "✅",
  close: "❌",
  search: "🔍",
  arrow: "→",
  user: "👤",
  briefcase: "💼",
  clock: "⏰",
  calendar: "📅",
  mail: "📧",
  phone: "📱",
  location: "📍",
  star: "⭐",
  heart: "❤️",
  assign: "🔗",
  eye: "👁️",
  chevronLeft: "◀",
  chevronRight: "▶",
};
